In [220]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [221]:
#    1. How many negative numbers are there?

print(np.count_nonzero(a < 0))
#print(f"{}")

4


In [222]:
#    2. How many positive numbers are there?

print(np.sum(a >0))


5


In [223]:
#    3. How many even positive numbers are there?

print(np.sum((a > 0) & (a%2 == 0)))

3


In [224]:
#    4. If you were to add 3 to each data point, 
#       how many positive numbers would there be?

b=a+3

print(np.sum(b<0))

2


In [225]:
#    5. If you squared each number, what would 
#       the new mean and standard deviation be?
squared=a**2

print(f"Original List: \t {a}")
print(f"Each squared: \t {squared}")



Original List: 	 [ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
Each squared: 	 [ 16 100 144 529   4   1   0   0   0  36   9  49]


In [226]:
#    6. A common statistical operation on a dataset is centering.
#       This means to adjust the data such that the mean of the
#       data is 0. This is done by subtracting the mean from each
#       data point. Center the data set. See this link for more on
#       centering.

import statistics as st

list_average = st.mean(a)

centered = a-list_average

print(f"Centered: \t {centered}")

#OTHER VERSION
#a.mean()
#create function to center data
#center_function = lambda x: x - x.mean()
#apply function to original NumPy array
#data_centered = center_function(a)
#view updated Array
#data_centered
#data_centered.mean()

Centered: 	 [  1   7   9  20  -5  -4  -3  -3  -3  -9   0 -10]


In [227]:
#    7. Calculate the z-score for each data point. Recall that the
#       z-score is given by:

#       z = (x-avg)/std
test_total = a.sum()
test_average = (test_total/a.size)

#print(test_total)
#print(test_average)
print(a)

#test_std = st.pstdev(a)
test_std = st.stdev(a)
print(test_std)

#z_scores2 = ( a - ( test_average ) )    /    st.pstdev(a)

z_scores = ( a - ( st.mean(a) ) )    /    st.stdev(a)

print(f"Z-Scores: \t {z_scores}")
#print(f"Z-Scores: \t {z_scores2}")

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
8.366600265340756
Z-Scores: 	 [ 0.11952286  0.83666003  1.07570575  2.39045722 -0.5976143  -0.47809144
 -0.35856858 -0.35856858 -0.35856858 -1.07570575  0.         -1.19522861]


In [ ]:
#    8. Copy the setup and exercise directions from More
#       Numpy Practice into your numpy_exercises.py and 
#       add your solutions.       

In [228]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# Use python's built in functionality/operators to determine the following:
# 1 - 8

In [193]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
print(sum_of_a)

55


In [194]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
print(min_of_a)

1


In [239]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
print(max_of_a)

10


In [217]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
sum_list = 0
for i in a:
    sum_list+=i

mean_of_a = sum_list/ len(a)

print(mean_of_a)

[4.5 5.5 6.5]


In [188]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.product(a)
print(product_of_a)

3628800


In [192]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
print(squares_of_a)

[  1   4   9  16  25  36  49  64  81 100]


In [218]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a[a % 2 == 1]
print(odds_in_a)

[3 5 7]


In [219]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a % 2 == 0]
print(evens_in_a)

[4 6 8]


In [251]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]
# 1 - 12
c=np.asarray(b)

In [235]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [236]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

# Presentation Answer 1 \# 11 (1)

In [242]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

b_array = np.array(b)

indices = np.where(b_array == b_array.max())
print(b_array[indices])

[8]


In [241]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
b.mean()

AttributeError: 'list' object has no attribute 'mean'

In [240]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
np.prod(b)

20160

In [243]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares=b**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
b[b%2 !=0]

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
b[b%2 ==0]

In [247]:
# Exercise 9 - print out the shape of the array b.
b.shape()

TypeError: 'tuple' object is not callable

In [ ]:
# Exercise 10 - transpose the array b.
np.transpose(b)

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
np.b.reshape(1,6)

In [252]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
np.b.reshape(6,1)

AttributeError: module 'numpy' has no attribute 'c'

In [254]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

c = np.array(c)

In [255]:
# Exercise 1 - Find the min, max, sum, and product of c.
np.min(c)
np.max(c)
np.sum(c)

45

In [256]:
# Exercise 2 - Determine the standard deviation of c.
np.std(c)

2.581988897471611

In [258]:
# Exercise 3 - Determine the variance of c.
np.var(c)

6.666666666666667

In [259]:
# Exercise 4 - Print out the shape of the array c
np.shape(c)

(3, 3)

In [260]:
# Exercise 5 - Transpose c and print out transposed result.
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [262]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [268]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
transposed_list = np.transpose(c)
np.sum(c*transposed_list)

261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
transposed_list = np.transpose(c)
np.prod(c*transposed_list)

In [274]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d=np.array(d)

In [271]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

# Presentation Answer 2 \# 11 (2)

In [230]:
# Exercise 2 - Find the cosine of all the numbers in d
d_cos = np.cos(d)
print(d_cos)

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [272]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [275]:
# Exercise 4 - Find all the negative numbers in d
d[d<0]

array([-90, -30, -45, -45])

In [276]:
# Exercise 5 - Find all the positive numbers in d
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [278]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [280]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [281]:
# Exercise 8 - Print out the shape of d.
np.shape(d)

(3, 6)

In [283]:
# Exercise 9 - Transpose and then print out the shape of d.
np.shape(np.transpose(d))

(6, 3)

In [286]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [ ]:
#    BONUS2. Awesome Bonus For much more practice with numpy, Go to https://github.com/rougier/numpy-100 
#            and clone the repo down to your laptop. To clone a repository: - Copy the SSH address of
#            the repository - cd ~/codeup-data-science - Then type git clone git@github.com:rougier/numpy-100.git - 
#            Now do cd numpy-100 on your terminal. - Type git remote remove origin, so you won't accidentally 
#            try to push your work to Rougier's repo.

#            Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to 
#            make a new, blank, repository on GitHub.

#            Go to https://github.com/new to make a new repo. Name it numpy-100.
       
#            DO NOT check any check boxes. We need a blank, empty repo.
      
#            Finally, follow the directions to "push an existing repository from 
#            the command line" so that you can push up your changes to your own account.
#            Now do work, add it, commit it, and push it!